# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-01 16:37
from __future__ import unicode_literals

import aldryn_bootstrap3.model_fields
import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '0006_auto_20160623_1627'),
        ('aldryn_bootstrap3', '0008_auto_20160820_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bootstrap3ButtonPlugin',
            fields=[
                ('link_url', models.URLField(blank=True, default='', verbose_name='link')),
                ('link_anchor', models.CharField(blank=True, help_text='Adds this value as an anchor (#my-anchor) to the link.', max_length=128, verbose_name='anchor')),
                ('link_mailto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='mailto')),
                ('link_phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='Phone')),
                ('link_target', models.CharField(blank=True, choices=[('', 'same window'), ('_blank', 'new window'), ('_parent', 'parent window'), ('_top', 'topmost frame')], max_length=100, verbose_name='target')),
                ('link_attributes', djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Link Attributes')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(blank=True, default='', max_length=256, verbose_name='label')),
                ('type', aldryn_bootstrap3.model_fields.LinkOrButton(default='lnk', max_length=10)),
                ('btn_context', aldryn_bootstrap3.model_fields.Context(default=b'default', max_length=255, verbose_name='context')),
                ('btn_size', aldryn_bootstrap3.model_fields.Size(blank=True, default='md', max_length=255, verbose_name='size')),
                ('btn_block', models.BooleanField(default=False, verbose_name='block')),
                ('txt_context', aldryn_bootstrap3.model_fields.Context(blank=True, default=b'default', max_length=255, verbose_name='context')),
                ('icon_left', aldryn_bootstrap3.model_fields.Icon(blank=True, default='', max_length=255)),
                ('icon_right', aldryn_bootstrap3.model_fields.Icon(blank=True, default='', max_length=255)),
                ('classes', aldryn_bootstrap3.model_fields.Classes(blank=True, default='', help_text='space separated classes that are added to the class. see <a href="http://getbootstrap.com/css/" target="_blank">bootstrap docs</a>')),
                ('responsive', aldryn_bootstrap3.model_fields.Responsive(blank=True, default='')),
                ('responsive_print', aldryn_bootstrap3.model_fields.ResponsivePrint(blank=True, default='')),
                ('link_file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.File', verbose_name='file')),
                ('link_page', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
        migrations.CreateModel(
            name='Bootstrap3LabelPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(blank=True, default='', max_length=256, verbose_name='label')),
                ('context', aldryn_bootstrap3.model_fields.Context(default=b'default', max_length=255)),
                ('classes', aldryn_bootstrap3.model_fields.Classes(blank=True, default='', help_text='space separated classes that are added to the class. see <a href="http://getbootstrap.com/css/" target="_blank">bootstrap docs</a>')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Bootstrap3PanelPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin')),
                ('context', aldryn_bootstrap3.model_fields.Context(default=b'default', max_length=255)),
                ('classes', aldryn_bootstrap3.model_fields.Classes(blank=True, default='', help_text='space separated classes that are added to the class. see <a href="http://getbootstrap.com/css/" target="_blank">bootstrap docs</a>')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RenameModel(
            old_name='Boostrap3AlertPlugin',
            new_name='Bootstrap3AlertPlugin',
        ),
        migrations.RenameModel(
            old_name='Boostrap3BlockquotePlugin',
            new_name='Bootstrap3BlockquotePlugin',
        ),
        migrations.RenameModel(
            old_name='Boostrap3IconPlugin',
            new_name='Bootstrap3IconPlugin',
        ),
        migrations.RenameModel(
            old_name='Boostrap3ImagePlugin',
            new_name='Bootstrap3ImagePlugin',
        ),
        migrations.RenameModel(
            old_name='Boostrap3PanelBodyPlugin',
            new_name='Bootstrap3PanelBodyPlugin',
        ),
        migrations.RenameModel(
            old_name='Boostrap3PanelFooterPlugin',
            new_name='Bootstrap3PanelFooterPlugin',
        ),
        migrations.RenameModel(
            old_name='Boostrap3PanelHeadingPlugin',
            new_name='Bootstrap3PanelHeadingPlugin',
        ),
        migrations.RenameModel(
            old_name='Boostrap3SpacerPlugin',
            new_name='Bootstrap3SpacerPlugin',
        ),
        migrations.RenameModel(
            old_name='Boostrap3WellPlugin',
            new_name='Bootstrap3WellPlugin',
        ),
        migrations.RemoveField(
            model_name='boostrap3buttonplugin',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='boostrap3buttonplugin',
            name='link_file',
        ),
        migrations.RemoveField(
            model_name='boostrap3buttonplugin',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='boostrap3labelplugin',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='boostrap3panelplugin',
            name='cmsplugin_ptr',
        ),
        migrations.AlterField(
            model_name='bootstrap3accordionitemplugin',
            name='context',
            field=aldryn_bootstrap3.model_fields.Context(default=b'default', max_length=255),
        ),
        migrations.AlterField(
            model_name='bootstrap3listgroupitemplugin',
            name='context',
            field=aldryn_bootstrap3.model_fields.Context(blank=True, default=b'default', max_length=255),
        ),
        migrations.DeleteModel(
            name='Boostrap3ButtonPlugin',
        ),
        migrations.DeleteModel(
            name='Boostrap3LabelPlugin',
        ),
        migrations.DeleteModel(
            name='Boostrap3PanelPlugin',
        ),
    ]
